### ISSUE TITLE
License of the project

### ISSUE THREAD

**Issue by ngleb** [imomaliev/tmux-bash-completion#5]
Good day!

Could you please clarify under which license this product should be distributed?

tmux completion once were in the tree of the tmux source code, but since 2.3 was removed. So now Gentoo maintainers would like to add a separate package to the tree to include this functionality and this won't be possible without knowing the license.

https://bugs.gentoo.org/show_bug.cgi?id=604688

**Comment by imomaliev** [comment]
@ngleb Good day to you too!

Good question. Never actually gotten to properly address licensing issue, on this project. I've decided to use GNU GPL 2.0 as many others completion scripts do. https://github.com/imomaliev/tmux-bash-completion/blob/master/COPYING.
